# https://github.com/foo-dogsquared/hugo-theme-arch-terminal/blob/master/MANUAL.adoc
baseURL = "https://andrewzah.com/"
languageCode = "en-us"
theme = "minimalist"
summaryLength = 15
canonifyUrls = true
toc = true
destination = "./public"
title = "Andrew Zah"

[author]
  name = "Andrew Zah"
  email = "zah@andrewzah.com"

[markup]
  [markup.asciidocext]
    extensions = ["asciidoctor-html5s", "asciidoctor-diagram"]
    workingFolderCurrent = true

  [markup.asciidocext.attributes]
    my-base-url = "https://andrewzah.com/"

[security]
  [security.exec]
    allow = [ "asciidoctor" ]
    osEnv = ['(?i)^(PATH|HOME|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[menu]
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "contact/"

  [[menu.main]]
    identifier = "cats"
    name = "cats"
    url = "cats/"

  [[menu.main]]
    identifier = "friends"
    name = "friends"
    url = "friends/"

  [[menu.main]]
    identifier = "openbook"
    name = "openbook"
    url = "openbook/"
