# https://github.com/foo-dogsquared/hugo-theme-arch-terminal/blob/master/MANUAL.adoc
baseURL = "https://andrewzah.com/"
languageCode = "en-us"
description = "my description"
theme = "zah"
summaryLength = 15
canonifyUrls = true
toc = true
destination = "./public"
title = "Andrew Zah"

[author]
    name = "Andrew Zah"
    email = "zah@andrewzah.com"

[markup]
  [markup.asciidocext]
    extensions = ["asciidoctor-html5s", "asciidoctor-diagram"]
    workingFolderCurrent = true

    [markup.asciidocext.attributes]
        my-base-url = "https://andrewzah.com/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "contact/"

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "index.xml/"

