# https://github.com/foo-dogsquared/hugo-theme-arch-terminal/blob/master/MANUAL.adoc
baseURL = "https://andrewzah.com/"
languageCode = "en-us"
description = "my description"
theme = "zah"
summaryLength = 15
paginate = 10
canonifyUrls = true
toc = true
destination = "public"

[author]
    name = "Andrew Zah"
    email = "zah@andrewzah.com"

[markup]
  [markup.asciidocext]
    args = ["--no-header-footer", "-r", "asciidoctor-html5s", "-b", "html5s", "-r", "asciidoctor-diagram"]
    workingFolderCurrent = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "contact/"

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "index.xml/"

