# https://github.com/foo-dogsquared/hugo-theme-arch-terminal/blob/master/MANUAL.adoc
baseURL = "https://andrewzah.com/"
languageCode = "en-us"
theme = "zah"
summaryLength = 15
canonifyUrls = true
toc = true
destination = "./public"
title = "Andrew Zah"
enableGitInfo = true

[params.author]
name = "Andrew Zah"
email = "zah@andrewzah.com"

[taxonomies]
  tag = 'tags'
  #series = 'series'

[markup]
  [markup.asciidocext]
    extensions = ["asciidoctor-html5s", "asciidoctor-diagram"]
    workingFolderCurrent = true

  [markup.asciidocext.attributes]
    my-base-url = "https://andrewzah.com/"

[security]
  [security.exec]
    allow = [ "asciidoctor" ]
    osEnv = ['(?i)^(PATH|HOME|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "about/"

  [[menu.main]]
    identifier = "cats"
    name = "cats"
    url = "cats/"

  [[menu.main]]
    identifier = "openbook"
    name = "openbook"
    url = "openbook/"

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "posts/"

  [[menu.main]]
    identifier = "reviews"
    name = "reviews"
    url = "reviews/"
