+++
title = "Philips TAH7508 Bluetooth Headphones"
slug = "philips-tah7508-bluetooth-headphones"
date = "2024-08-18"
lastmod = "2024-09-18"
tags = ["audio"]
description = "A look at the Philips TAH7508 Bluetooth Headphones."
+++

= Philips TAH7508 Bluetooth Headphones

I generally travel with earbuds in order to cut down on luggage size, but
on some days I find it quite hard to get work done and shut out the distractions.

I was looking around on
https://en.wikipedia.org/wiki/Coupang[Coupang] (a Korean shopping app),
and found these
https://www.documents.philips.com/assets/20240407/e672ddd5487b47d189dcb14b002fccbe.pdf[Philips TAH5708 headphones].

These stats got me interested:

* 60 hours of usage, or 45 with noise reduction enabled.
* charging via usb-c
* compact folding
* a 3.5mm audio jack (wow!) + included 3.5mm male-male cable

All for less than $60 USD, so I figured why not?

NOTE: I didn't see this until researching for this article, but when I search TAH7508,
only Korean results seem to pop up. Additionally, the
https://www.usa.philips.com/c-m-so/headphones/latest#availability=all[Philips USA website]
only lists models up to 6xxx, so I'm not sure if this is specific to Korea. The
https://www.amazon.com/dp/B0D8N8HLW6[H6509 model] seems similar, but the foam doesn't look
nearly as nice as the TAH7508.

== Initial Thoughts

The headphones feel sturdy, and the foam is nice.
I was able to wear them for multiple hours without feeling pressure on my glasses.

Being able to pair to multiple devices is quite handy as I frequently switch between
three laptops. All I have to do is disconnect with one and connect with another,
**no app required**. I can't begin to tell you how much the Bose app annoys me,
so this is a much welcome change.

Though, there is a Philips app for things like settings and firmware updates.

== Update: 1 Month

Overall I'm very happy with how these have held up so far.

I use them just about daily for multiple-hour calls via discord and listening to music,
charging every 2-3 days.

The battery life is long enough that I don't find myself worrying at all.

== Info

I purchased these on Coupang for ₩71,000 KRW(roughly $58.30 USD) on 8/11 and got them on 8/12.

CAUTION: This is a review after ~1 week of usage.
I will update this review after a few months to see how it holds up.

// Copyright 2016-2024 Andrew Zah
